server:
  port: 8761

spring:
  application:
    name: ServiceRegistry

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Eureka Server does not register itself
    fetch-registry: false         # No need to fetch registry since it's the server
