spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables service discovery for gateway
          lower-case-service-id: false
      routes:
        - id: user-service
          uri: lb://UserService
          predicates:
            - Path=/api/users/**
        - id: rating-service
          uri: lb://RatingService
          predicates:
            - Path=/api/ratings/**
        - id: hotel-service
          uri: lb://HotelService
          predicates:
            - Path=/api/hotels/**,/api/staffs/**

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true